version: "3.5"

services:
  softhsm:
    image: softhsm2:2.6.1
    build: .
    container_name: softhsm2
    environment:
      PKCS11_DAEMON_SOCKET: "tcp://0.0.0.0:5555"
    ports:
      - "5555:5555"
